[build]
  publish = "."

[[redirects]]
  from = "/"
  to = "/galerie-auryn 1.html"
  status = 200

[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
